// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed NotoSansCJKkr-Regular.otf
var resourceNotoSansCJKkrRegularOtfData []byte
var resourceNotoSansCJKkrRegularOtf = &fyne.StaticResource{
	StaticName:    "NotoSansCJKkr-Regular.otf",
	StaticContent: resourceNotoSansCJKkrRegularOtfData,
}

//go:embed NotoSansCJKkr-Bold.otf
var resourceNotoSansCJKkrBoldOtfData []byte
var resourceNotoSansCJKkrBoldOtf = &fyne.StaticResource{
	StaticName:    "NotoSansCJKkr-Bold.otf",
	StaticContent: resourceNotoSansCJKkrBoldOtfData,
}

//go:embed icon.png
var resourceIconPngData []byte
var resourceIconPng = &fyne.StaticResource{
	StaticName:    "icon.png",
	StaticContent: resourceIconPngData,
}
